# Generated by Django 3.2.6 on 2021-08-27 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0003_fix_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('token', models.CharField(max_length=32, unique=True)),
                ('min_price', models.PositiveIntegerField(default=0)),
                ('max_price', models.PositiveIntegerField(default=0)),
                ('cities', models.ManyToManyField(blank=True, null=True, related_name='profiles', to='residences.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
