# Generated by Django 3.2.6 on 2021-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_fix_fields'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthdate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='residences.City'),
        ),
    ]
