# Generated by Django 3.2.6 on 2021-08-22 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corporations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('street', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=16)),
                ('postal_code', models.CharField(max_length=6)),
                ('neighbourhood', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('HOUSE_DETACHED', 'House'), ('HOUSE_SEMI_DETACHED', 'House Semi Detached'), ('HOUSE_DUPLEX', 'House Duplex'), ('HOUSE_TERRACED', 'House Terraced'), ('APARTMENT', 'Apartment'), ('MAISONNETTE', 'Maisonnette'), ('UNKNOWN', 'Unknown')], max_length=255)),
                ('price_base', models.PositiveIntegerField(blank=True, null=True)),
                ('price_service', models.PositiveIntegerField(blank=True, null=True)),
                ('price_benefit', models.PositiveIntegerField(blank=True, null=True)),
                ('price_total', models.PositiveIntegerField()),
                ('energy_labels', models.CharField(blank=True, max_length=1, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('floor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('has_elevator', models.BooleanField(blank=True, null=True)),
                ('available_at', models.DateField(blank=True, null=True)),
                ('reactions_ended_at', models.DateField(blank=True, null=True)),
                ('url', models.TextField()),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('floor_plan_url', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='residences.city')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='corporations.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('rank_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='corporations.corporation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
