# Generated by Django 3.2.6 on 2021-08-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0003_add_registration'),
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='user',
        ),
        migrations.AddField(
            model_name='reaction',
            name='registration',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='corporations.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reaction',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='residences.residence'),
        ),
    ]
