# Generated by Django 3.2.6 on 2021-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_fix_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residence',
            old_name='energy_labels',
            new_name='energy_label',
        ),
        migrations.AlterField(
            model_name='residence',
            name='reactions_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='residence',
            name='type',
            field=models.CharField(choices=[('HOUSE_DETACHED', 'House Detached'), ('HOUSE_SEMI_DETACHED', 'House Semi Detached'), ('HOUSE_DUPLEX', 'House Duplex'), ('HOUSE_TERRACED', 'House Terraced'), ('HOUSE_UNKNOWN', 'House Unknown'), ('APARTMENT', 'Apartment'), ('MAISONNETTE', 'Maisonnette'), ('UNKNOWN', 'Unknown')], max_length=255),
        ),
    ]
