# Generated by Django 3.2.6 on 2021-08-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0003_add_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporation',
            name='handle',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
