# Generated by Django 3.2.7 on 2021-09-18 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


def add_unknown_platform(apps, schema_editor):
    Platform = apps.get_model('corporations', 'Platform')
    platform = Platform(id='846f2be7-cc94-44cc-9ea2-9554a5440168', name='Unknown', handle='unknown')
    platform.save()


def delete_unknown_platform(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Platform = apps.get_model('corporations', 'Platform')
    Platform.objects.using(db_alias).get(id='846f2be7-cc94-44cc-9ea2-9554a5440168').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('corporations', '0004_fix_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('handle', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='corporation',
            name='platforms',
            field=models.ManyToManyField(related_name='corporations', to='corporations.Platform'),
        ),
        migrations.RunPython(add_unknown_platform, delete_unknown_platform),
        migrations.AddField(
            model_name='registration',
            name='platform',
            field=models.ForeignKey(default='846f2be7-cc94-44cc-9ea2-9554a5440168', on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='corporations.platform'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='registration',
            name='corporation',
        ),
    ]
