# Generated by Django 3.2.6 on 2021-08-27 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import woningzoeker.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('EMAIL', 'Email'), ('TELEGRAM', 'Telegram')], max_length=255)),
                ('credentials', woningzoeker.fields.EncryptedJSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_providers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
