# Generated by Django 3.2.6 on 2021-08-27 17:17

from django.db import migrations
import woningzoeker.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_identitifer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprovider',
            name='credentials',
            field=woningzoeker.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
